### ISSUE TITLE
Wrong Python version in setup.py

### ISSUE THREAD

**Issue by Suxixx** [jhelgert/IliasDownloaderUniMA#15]
**Wrong Python version in setup.py**
```python
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```
(from https://docs.python.org/3/library/datetime.html)
classmethod date.fromisoformat(date_string)
Return a date corresponding to a date_string given in the format YYYY-MM-DD:

>>>
>>> from datetime import date
>>> date.fromisoformat('2019-12-04')
datetime.date(2019, 12, 4)
This is the inverse of date.isoformat(). It only supports the format YYYY-MM-DD.

New in version 3.7.
**Solution**
Increase required Python Version to 3.7+

**Comment by jhelgert** [comment]
Thanks! Fixed.
