### ISSUE TITLE
IndexError _parseFileProperties

### ISSUE THREAD

**Issue by Suxixx** [jhelgert/IliasDownloaderUniMA#19]
**Describe the bug**

```python
Exception has occurred: IndexError
list index out of range
line 172, in _parseFileProperties file_size = float(file_size_tmp[0])
```
![image](https://user-images.githubusercontent.com/44966038/95906181-172ecd80-0d9a-11eb-8c06-0f43216b98bd.png)

```
source:<bs4.element.SoupStrainer object at 0x7fd58c4ff550>
0:<span class="il_ItemProperty">
		
		Dateiendung fehlt  </span>
1:<span class="il_ItemProperty">
		
		  </span>
2:<span class="il_ItemProperty">
		
		739 Bytes  </span>
``` 
Course ID: 1019887
Path to file: Datenbanksysteme I [V] [1. PG] (HWS 2020) Übung Quellcode Blatt 08 7_Implementierung_Normalform-Tests_Zerlegungsalgorithmen Java

**Comment by jhelgert** [comment]
Thanks! Should be fixed now, I'll upload the new version to pip in a few minutes.

PS: Would be happy to accept pull requests in the future :)
