### ISSUE TITLE
Some courses crash the addCourse function

### ISSUE THREAD

**Issue by GityUpNow** [jhelgert/IliasDownloaderUniMA#22]
**Describe the bug**
The breadcrumbs of courses seem to be inconsistent. 
Some courses have only two instead of three li tags in their breadcrumb.
addCourse expects the breadcrumb to have three, so it crashes when parsing the course name.

The only course I found so far that suffers from this has the ref_id 342184.

I tried to write a fix [here](https://github.com/jhelgert/IliasDownloaderUniMA/pull/21/commits/f6af8e8931d20a6c312edef3f459d427f5fce262)

```python
Traceback (most recent call last):
  File "download.py", line 7, in <module>
    m.addCourse(342184)
  File "/home/gity/temp/IliasDownloaderUniMA/IliasDownloaderUniMA/__init__.py", line 113, in addCourse
    course_name = soup.find_all("ol", "breadcrumb")[0].find_all('li')[2].get_text()
IndexError: list index out of range

```

**Expected behavior**
addCourse should work with every Course.

**Comment by jhelgert** [comment]
See my comment in the review for #21. Since we only want to scan regular semester courses, I'll close this one.
